# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6.3
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.3
        
    - name: Run pylint
      run: |
        pylint --disable=R,C,I,W0703,W0511
    - name: Run flake8
      run: |
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics
        --ignore=N806,N812,W504 --exclude=__init__.py,*/migrations/*,*/pix4d/settings/*:  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
